//Data until the ai model is trained

export const MvpData = [
    
    //Under 5 euros
    [
        //Hobbies with one interest (30 for each)


        //Hobbies with pair of two interests (10 for each)

        //Creative and mental hobbies
        ["Book-themed Playing Cards", "Playing cards featuring classic book covers", ["Reading (e.g., Fiction, Non-fiction)", "Gaming (e.g., Board Games, Video Games)"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Bookmark with Built-in Dice", "A functional bookmark that also acts as a die for gaming", ["Reading (e.g., Fiction, Non-fiction)", "Gaming (e.g., Board Games, Video Games)"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Mini Book Puzzle", "A small puzzle that forms a book when completed", ["Reading (e.g., Fiction, Non-fiction)", "Gaming (e.g., Board Games, Video Games)"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["DIY Miniature Bookshelf for Board Games", "A small DIY project to make a miniature bookshelf for board game pieces", ["Reading (e.g., Fiction, Non-fiction)", "Gaming (e.g., Board Games, Video Games)"], ["Young Adult", "Adult"], [], "More Practical", "both", "both"],
        ["Board Game-themed Bookends", "Bookends that are designed with a board game theme", ["Reading (e.g., Fiction, Non-fiction)", "Gaming (e.g., Board Games, Video Games)"], ["Adult", "Senior"], ["Birthday", "Christmas", "Anniversary"], "More Enjoyable", "both", "both"],
        ["Magnetic Book and Game Holder", "A device that holds a book open and also has areas to hold game pieces", ["Reading (e.g., Fiction, Non-fiction)", "Gaming (e.g., Board Games, Video Games)"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Literature Trivia Game", "A trivia game focused on literature and book knowledge", ["Reading (e.g., Fiction, Non-fiction)", "Gaming (e.g., Board Games, Video Games)"], ["Adult", "Senior"], [], "More Enjoyable", "both", "both"],
        ["DIY Dice Tower with Book Decor", "A DIY dice tower that has book-themed decorations", ["Reading (e.g., Fiction, Non-fiction)", "Gaming (e.g., Board Games, Video Games)"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Story Dice", "Dice that help in creating stories, enhancing both reading and gaming experience", ["Reading (e.g., Fiction, Non-fiction)", "Gaming (e.g., Board Games, Video Games)"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Book Cover for Board Games", "A book cover that can also be used to store or camouflage board games", ["Reading (e.g., Fiction, Non-fiction)", "Gaming (e.g., Board Games, Video Games)"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
    
        ["Manga-themed Bookmarks", "Beautiful bookmarks featuring popular manga characters", ["Reading (e.g., Fiction, Non-fiction)", "Anime/Manga"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Chibi Character Page Holder", "A cute chibi character that holds the pages of your book", ["Reading (e.g., Fiction, Non-fiction)", "Anime/Manga"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Manga Cover Notebook", "A notebook with a cover inspired by popular manga series", ["Reading (e.g., Fiction, Non-fiction)", "Anime/Manga"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Anime Quote Bookmarks", "Bookmarks featuring famous and inspiring quotes from various anime", ["Reading (e.g., Fiction, Non-fiction)", "Anime/Manga"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["DIY Paper Craft Manga Characters", "Paper crafting kit to create manga characters", ["Reading (e.g., Fiction, Non-fiction)", "Anime/Manga"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Manga Drawing Guide for Beginners", "A beginner's guide book to drawing manga characters", ["Reading (e.g., Fiction, Non-fiction)", "Anime/Manga"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Mini Manga Puzzles", "Small puzzles featuring scenes or characters from popular manga", ["Reading (e.g., Fiction, Non-fiction)", "Anime/Manga"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Book Sleeves with Anime Designs", "Protective sleeves for books with beautiful anime designs", ["Reading (e.g., Fiction, Non-fiction)", "Anime/Manga"], ["Young Adult", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Anime/Manga Story Cubes", "Dice with images for creating your own anime or manga stories", ["Reading (e.g., Fiction, Non-fiction)", "Anime/Manga"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Manga Scene Bookmarks", "Bookmarks that represent various scenes from popular manga series", ["Reading (e.g., Fiction, Non-fiction)", "Anime/Manga"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        
        ["Paintable Book Cover", "A customizable book cover that one can paint or draw on", ["Reading (e.g., Fiction, Non-fiction)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Coloring Bookmarks", "Bookmarks that can be colored in with various designs", ["Reading (e.g., Fiction, Non-fiction)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["DIY Bookends Crafting Kit", "A kit to create custom, artistic bookends", ["Reading (e.g., Fiction, Non-fiction)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Art-themed Bookmarks", "Bookmarks featuring famous paintings and artworks", ["Reading (e.g., Fiction, Non-fiction)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Young Adult", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Book Cover Design Kit", "A set that allows customization of book covers with artistic designs", ["Reading (e.g., Fiction, Non-fiction)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Literature Quote Prints", "Printable artworks featuring quotes from classic literature", ["Reading (e.g., Fiction, Non-fiction)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Adult", "Senior"], ["Birthday", "Christmas", "Anniversary"], "More Enjoyable", "both", "both"],
        ["Craft Paper Books", "Books made of craft paper for doodling or sketching", ["Reading (e.g., Fiction, Non-fiction)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Drawing Techniques Book", "A book detailing various drawing techniques and practices", ["Reading (e.g., Fiction, Non-fiction)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Art Supply Organizer with Bookshelf", "An organizer that holds art supplies and has a space for books", ["Reading (e.g., Fiction, Non-fiction)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Young Adult", "Adult"], [], "More Practical", "both", "both"],
        ["Literary Art Stencils", "Stencils of quotes or images from famous literature for artistic projects", ["Reading (e.g., Fiction, Non-fiction)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
    
        ["LED Book Light", "A clip-on LED light for night-time reading", ["Reading (e.g., Fiction, Non-fiction)", "Tech and Gadgets"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Bookish USB Flash Drive", "A USB flash drive designed to look like a mini book", ["Reading (e.g., Fiction, Non-fiction)", "Tech and Gadgets"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Book-themed Phone Stand", "A phone stand that looks like a book or features a literary design", ["Reading (e.g., Fiction, Non-fiction)", "Tech and Gadgets"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Electronic Dictionary Bookmark", "A bookmark that also functions as an electronic dictionary", ["Reading (e.g., Fiction, Non-fiction)", "Tech and Gadgets"], ["Young Adult", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Magnetic Page Markers with Tech Designs", "Magnetic page markers featuring designs inspired by tech themes", ["Reading (e.g., Fiction, Non-fiction)", "Tech and Gadgets"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["E-Reader Bean Bag Stand", "A comfortable bean bag stand to hold e-readers or tablets", ["Reading (e.g., Fiction, Non-fiction)", "Tech and Gadgets"], ["Adult", "Senior"], [], "More Enjoyable", "both", "both"],
        ["Tech-themed Bookends", "Bookends with a design inspired by tech gadgets", ["Reading (e.g., Fiction, Non-fiction)", "Tech and Gadgets"], ["Young Adult", "Adult"], [], "More Practical", "both", "both"],
        ["Book Title Generator", "A small electronic gadget that generates random book titles or plot ideas", ["Reading (e.g., Fiction, Non-fiction)", "Tech and Gadgets"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Book Cover Tablet Sleeve", "A tablet sleeve that resembles a book cover", ["Reading (e.g., Fiction, Non-fiction)", "Tech and Gadgets"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Literary Quote Keychain with LED Light", "A keychain featuring a literary quote and an LED light", ["Reading (e.g., Fiction, Non-fiction)", "Tech and Gadgets"], ["Adult", "Senior"], [], "More Enjoyable", "both", "both"],
        
        ["Book-themed Jigsaw Puzzle", "A jigsaw puzzle showcasing iconic book covers or literary scenes", ["Reading (e.g., Fiction, Non-fiction)", "Puzzle Solving"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Literary Crossword Book", "A book filled with crossword puzzles themed around classic literature", ["Reading (e.g., Fiction, Non-fiction)", "Puzzle Solving"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Bookmark Puzzle", "A bookmark that also serves as a mini puzzle to solve", ["Reading (e.g., Fiction, Non-fiction)", "Puzzle Solving"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Story Cubes", "Dice with images that help create a narrative or story", ["Reading (e.g., Fiction, Non-fiction)", "Puzzle Solving"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Literary Sudoku Book", "A Sudoku puzzle book that has challenges based on literary characters or books", ["Reading (e.g., Fiction, Non-fiction)", "Puzzle Solving"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
        ["3D Book Puzzle", "A 3D puzzle that forms a model of a famous book or literature scene", ["Reading (e.g., Fiction, Non-fiction)", "Puzzle Solving"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Bookshelf Logic Puzzle", "A logic puzzle game where players need to organize a bookshelf based on various hints", ["Reading (e.g., Fiction, Non-fiction)", "Puzzle Solving"], ["Young Adult", "Adult"], [], "More Practical", "both", "both"],
        ["Literary Quote Cipher", "A set of encrypted quotes from literature, challenging recipients to decode", ["Reading (e.g., Fiction, Non-fiction)", "Puzzle Solving"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Magnetic Poetry Puzzle Kit", "A set of magnetic words to form poetic phrases, also functioning as a puzzle", ["Reading (e.g., Fiction, Non-fiction)", "Puzzle Solving"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Classic Book Cover Brain Teasers", "Brain teasers or riddles presented within classic book cover designs", ["Reading (e.g., Fiction, Non-fiction)", "Puzzle Solving"], ["Adult", "Senior"], [], "More Enjoyable", "both", "both"],
        
        ["Bookish Photo Frames", "Photo frames that resemble book covers or have literary designs", ["Reading (e.g., Fiction, Non-fiction)", "Photography"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Photo Album that Looks Like a Book", "A photo album that externally resembles a classic book", ["Reading (e.g., Fiction, Non-fiction)", "Photography"], ["Adult", "Senior"], ["Birthday", "Christmas", "Anniversary"], "More Enjoyable", "both", "both"],
        ["Photography-themed Bookmarks", "Bookmarks featuring famous photographs or photography themes", ["Reading (e.g., Fiction, Non-fiction)", "Photography"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Literary Quotes on Photography", "Prints or cards featuring literary quotes related to photography", ["Reading (e.g., Fiction, Non-fiction)", "Photography"], ["Young Adult", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Camera Lens Cleaning Cloth with Book Quotes", "Lens cleaning cloths featuring quotes from literature", ["Reading (e.g., Fiction, Non-fiction)", "Photography"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["DIY Book Cover Photoshoot Kit", "A kit with props and backdrops for creating book cover-themed photos", ["Reading (e.g., Fiction, Non-fiction)", "Photography"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Photography Books for Kids", "Children’s books that explore the basics of photography", ["Reading (e.g., Fiction, Non-fiction)", "Photography"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Bookish Camera Strap", "A camera strap with literary quotes or bookish designs", ["Reading (e.g., Fiction, Non-fiction)", "Photography"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Photographer's Reading Light", "A portable and adjustable reading light that photographers can use during shoots", ["Reading (e.g., Fiction, Non-fiction)", "Photography"], ["Young Adult", "Adult"], [], "More Practical", "both", "both"],
        ["Storytelling Photo Prompts", "Cards or a book that offers photo prompts aimed at storytelling", ["Reading (e.g., Fiction, Non-fiction)", "Photography"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],

        ["Bookish Pop Socket", "A pop socket for phones/tablets featuring famous book covers or literary quotes", ["Reading (e.g., Fiction, Non-fiction)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Literary Movie Poster", "Posters of movies that were adapted from books, with a creative or vintage twist", ["Reading (e.g., Fiction, Non-fiction)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Book-themed Phone Stand", "A phone stand with designs or quotes from iconic books", ["Reading (e.g., Fiction, Non-fiction)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Bookmark with Built-in Timer", "A bookmark that helps track reading or screen time with a built-in timer", ["Reading (e.g., Fiction, Non-fiction)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Classic Book Cover Coasters", "Coasters featuring classic book covers, perfect for movie or reading nights", ["Reading (e.g., Fiction, Non-fiction)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
        ["Literary-themed Popcorn Box", "Popcorn boxes featuring quotes or images from classic literature for movie nights", ["Reading (e.g., Fiction, Non-fiction)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Adjustable Book and Tablet Stand", "A stand that can hold both books and tablets for convenient media consumption", ["Reading (e.g., Fiction, Non-fiction)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Young Adult", "Adult"], [], "More Practical", "both", "both"],
        ["Book and Movie Comparison Chart", "A chart that allows one to compare and analyze books and their movie adaptations", ["Reading (e.g., Fiction, Non-fiction)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Literature-based Music Playlists", "Curated music playlists based on famous books or literary themes (access via QR code)", ["Reading (e.g., Fiction, Non-fiction)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Young Adult", "Adult"], [], "More Practical", "both", "both"],
        ["Book-inspired Movie Night Kit", "A kit including themed accessories and snacks for watching movies based on books", ["Reading (e.g., Fiction, Non-fiction)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],

        ["Literary Recipe Cards", "Recipe cards inspired by meals in popular books and novels", ["Reading (e.g., Fiction, Non-fiction)", "Cooking or Baking"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Book-themed Cookie Cutters", "Cookie cutters shaped like bookish symbols or characters", ["Reading (e.g., Fiction, Non-fiction)", "Cooking or Baking"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Bookish Kitchen Towels", "Kitchen towels printed with quotes or images from beloved books", ["Reading (e.g., Fiction, Non-fiction)", "Cooking or Baking"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
        ["Literature-inspired Spices and Herbs", "Packages of spices or herbs with labels inspired by literary elements", ["Reading (e.g., Fiction, Non-fiction)", "Cooking or Baking"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Cookbook Bookmark", "A durable, easy-to-clean bookmark specially designed for cookbooks", ["Reading (e.g., Fiction, Non-fiction)", "Cooking or Baking"], ["Young Adult", "Adult"], [], "More Practical", "both", "both"],
        ["Bookish Oven Mitts", "Oven mitts featuring designs or quotes inspired by popular books", ["Reading (e.g., Fiction, Non-fiction)", "Cooking or Baking"], ["Adult", "Senior"], [], "More Enjoyable", "both", "both"],
        ["Literary Teas", "Tea blends inspired by different genres or famous authors and characters", ["Reading (e.g., Fiction, Non-fiction)", "Cooking or Baking"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Storytelling Kitchen Utensils", "Kitchen utensils that feature quotes or images from classic literature", ["Reading (e.g., Fiction, Non-fiction)", "Cooking or Baking"], ["Young Adult", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Edible Bookish Decorations", "Edible cake or cupcake decorations that are inspired by literary themes", ["Reading (e.g., Fiction, Non-fiction)", "Cooking or Baking"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Novel Nibbles", "Small snacks or candies packaged with literary themes or puns", ["Reading (e.g., Fiction, Non-fiction)", "Cooking or Baking"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
    
        ["Anime-themed Playing Cards", "Playing cards featuring characters or symbols from popular anime", ["Gaming (e.g., Board Games, Video Games)", "Anime/Manga"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Chibi Game Character Keychains", "Keychains featuring game characters in a cute chibi anime style", ["Gaming (e.g., Board Games, Video Games)", "Anime/Manga"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Gaming-inspired Manga", "Manga books that are based on or inspired by popular video games", ["Gaming (e.g., Board Games, Video Games)", "Anime/Manga"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Anime Game Board Mats", "Board game mats featuring anime designs or characters", ["Gaming (e.g., Board Games, Video Games)", "Anime/Manga"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Mini Anime-themed Puzzles", "Small puzzles featuring scenes or characters from anime that also have gaming adaptations", ["Gaming (e.g., Board Games, Video Games)", "Anime/Manga"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Gaming and Anime Sticker Sets", "Sticker sets that include various gaming and anime characters", ["Gaming (e.g., Board Games, Video Games)", "Anime/Manga"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Anime-inspired Dice Sets", "Dice sets that are designed or colored inspired by anime themes", ["Gaming (e.g., Board Games, Video Games)", "Anime/Manga"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Gaming Character Anime Figures", "Small figures or collectibles where gaming characters are depicted in anime styles", ["Gaming (e.g., Board Games, Video Games)", "Anime/Manga"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Manga Drawing Gaming Guides", "Guides that help in drawing manga versions of popular gaming characters", ["Gaming (e.g., Board Games, Video Games)", "Anime/Manga"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Anime and Gaming Coasters", "Coasters featuring designs inspired by both anime and gaming icons", ["Gaming (e.g., Board Games, Video Games)", "Anime/Manga"], ["Young Adult", "Adult"], [], "More Enjoyable", "both", "both"],

        ["DIY Gaming Character Origami", "Origami sheets and instructions to create gaming characters", ["Gaming (e.g., Board Games, Video Games)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Paint by Numbers Gaming Scenes", "A paint by numbers set featuring scenes or characters from popular games", ["Gaming (e.g., Board Games, Video Games)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Gaming Pixel Art Beads", "Beads that can be arranged and ironed to create gaming pixel art", ["Gaming (e.g., Board Games, Video Games)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Gaming-themed Coloring Book", "A coloring book filled with line art of popular gaming characters and scenes", ["Gaming (e.g., Board Games, Video Games)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Gamer Pencil & Pen Holders", "DIY craft kit to make pencil and pen holders shaped like gaming consoles or characters", ["Gaming (e.g., Board Games, Video Games)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Customizable Game Controller Skins", "Sticker skins for game controllers that one can color or design", ["Gaming (e.g., Board Games, Video Games)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Video Game Themed Craft Paper", "Craft paper featuring prints and designs inspired by popular video games", ["Gaming (e.g., Board Games, Video Games)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Gaming Character Clay Set", "Clay set to sculpt and create popular gaming characters", ["Gaming (e.g., Board Games, Video Games)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Game-themed Embroidery Kit", "Embroidery kits with patterns or designs based on gaming icons", ["Gaming (e.g., Board Games, Video Games)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
        ["Gaming Icon Stencils", "Stencils of gaming icons for artistic projects like painting or drawing", ["Gaming (e.g., Board Games, Video Games)", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
    
        ["Silicone Game Controller Grips", "Enhanced silicone grips for game controllers offering a comfortable gaming experience", ["Gaming (e.g., Board Games, Video Games)", "Tech and Gadgets"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["LED Gaming Mouse Pad", "Mouse pad with customizable LED lights to enhance the gaming setup", ["Gaming (e.g., Board Games, Video Games)", "Tech and Gadgets"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Gaming Console Dust Cover", "Dust covers designed for various gaming consoles to keep them clean", ["Gaming (e.g., Board Games, Video Games)", "Tech and Gadgets"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Game-themed USB Flash Drives", "USB flash drives designed to resemble popular gaming characters or accessories", ["Gaming (e.g., Board Games, Video Games)", "Tech and Gadgets"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Mini Screen Cleaner for Gamers", "Screen cleaners with game-themed designs suitable for various devices", ["Gaming (e.g., Board Games, Video Games)", "Tech and Gadgets"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Adjustable Mobile Gaming Stand", "A portable and adjustable stand for comfortable mobile gaming", ["Gaming (e.g., Board Games, Video Games)", "Tech and Gadgets"], ["Young Adult", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Gaming Cable Organizers", "Cable organizers featuring designs inspired by gaming icons", ["Gaming (e.g., Board Games, Video Games)", "Tech and Gadgets"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Game-inspired Phone Grips", "Phone grips that feature designs or logos from popular games", ["Gaming (e.g., Board Games, Video Games)", "Tech and Gadgets"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Gaming-themed Earbud Cases", "Cases for earbuds or headphones with designs inspired by popular games", ["Gaming (e.g., Board Games, Video Games)", "Tech and Gadgets"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Portable Game Controller Keychain", "Mini game controller keychains that can be attached to gadgets", ["Gaming (e.g., Board Games, Video Games)", "Tech and Gadgets"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],

        ["Game-themed Puzzle Cubes", "Twisting puzzles inspired by popular game characters or themes", ["Gaming (e.g., Board Games, Video Games)", "Puzzle Solving"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Video Game Logic Puzzles", "Books of logic puzzles that are themed around various video games", ["Gaming (e.g., Board Games, Video Games)", "Puzzle Solving"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Puzzle-solving Video Game Merchandise", "Merchandise from video games that involve significant puzzle-solving elements", ["Gaming (e.g., Board Games, Video Games)", "Puzzle Solving"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Jigsaw Puzzles with Gaming Scenes", "Jigsaw puzzles that depict various scenes from popular video games", ["Gaming (e.g., Board Games, Video Games)", "Puzzle Solving"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Brain-Training Video Game Workbook", "Workbooks inspired by brain-training video games with various puzzles", ["Gaming (e.g., Board Games, Video Games)", "Puzzle Solving"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
        ["Gamer-themed Sudoku Books", "Sudoku puzzle books with a cover or theme relating to popular games", ["Gaming (e.g., Board Games, Video Games)", "Puzzle Solving"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Game-inspired Mystery Puzzles", "Mystery puzzles that are inspired by detective or mystery games", ["Gaming (e.g., Board Games, Video Games)", "Puzzle Solving"], ["Young Adult", "Adult"], [], "More Practical", "both", "both"],
        ["Video Game Crossword Puzzles", "Crossword puzzles that incorporate terminology and themes from various video games", ["Gaming (e.g., Board Games, Video Games)", "Puzzle Solving"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Educational Gaming Puzzle Cards", "Cards featuring puzzles and challenges inspired by educational video games", ["Gaming (e.g., Board Games, Video Games)", "Puzzle Solving"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Gaming Strategy Puzzle Book", "Books containing puzzles that help in enhancing strategic thinking in gaming", ["Gaming (e.g., Board Games, Video Games)", "Puzzle Solving"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],

        ["Gaming-themed Photo Frames", "Photo frames adorned with elements and icons from popular games", ["Gaming (e.g., Board Games, Video Games)", "Photography"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Camera Lens Cap with Game Designs", "Custom lens caps featuring designs or logos from popular video games", ["Gaming (e.g., Board Games, Video Games)", "Photography"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Video Game Scenery Backdrops", "Photography backdrops featuring sceneries or themes from popular video games", ["Gaming (e.g., Board Games, Video Games)", "Photography"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Game Controller Tripod Mount", "A tripod mount shaped like a game controller for holding cameras or smartphones", ["Gaming (e.g., Board Games, Video Games)", "Photography"], ["Young Adult", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Photo Editing Software with Game Filters", "Software for editing photos with special filters or effects inspired by video games", ["Gaming (e.g., Board Games, Video Games)", "Photography"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Gaming-themed Camera Straps", "Durable camera straps featuring designs or logos from popular games", ["Gaming (e.g., Board Games, Video Games)", "Photography"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Photography Quest Cards (Gaming Edition)", "Challenge cards that present photography quests or tasks based on gaming themes", ["Gaming (e.g., Board Games, Video Games)", "Photography"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Game Icon Photo Clips", "Photo clips or holders featuring popular icons or elements from video games", ["Gaming (e.g., Board Games, Video Games)", "Photography"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Video Game-themed Album", "Photo albums designed with covers or themes inspired by popular video games", ["Gaming (e.g., Board Games, Video Games)", "Photography"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Gaming Sticker Sets for Camera", "Sticker sets featuring gaming elements for decorating cameras or accessories", ["Gaming (e.g., Board Games, Video Games)", "Photography"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
    
        ["Gaming-themed Popcorn Boxes", "Cardboard popcorn boxes with gaming graphics for snack during gaming or watching media", ["Gaming (e.g., Board Games, Video Games)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], ["Birthday", "Other/No Specific Occasion"], "More Practical", "both", "both"],
        ["Video Game Inspired Coasters", "Coasters featuring designs from popular games, suitable for a media watching session", ["Gaming (e.g., Board Games, Video Games)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Game Controller-shaped Remote Holder", "A holder for remotes and controllers, shaped like a game controller", ["Gaming (e.g., Board Games, Video Games)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Young Adult", "Adult"], [], "More Practical", "both", "both"],
        ["Gaming Soundtracks CD", "A CD collection of memorable and popular soundtracks from various video games", ["Gaming (e.g., Board Games, Video Games)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Game-themed Blanket", "A warm blanket featuring prints from popular video games for cozy media watching", ["Gaming (e.g., Board Games, Video Games)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Mini Game Console with Retro Games", "A miniature game console keychain that includes playable retro games", ["Gaming (e.g., Board Games, Video Games)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Gaming Movie Poster", "Posters of movies that are based on or inspired by popular video games", ["Gaming (e.g., Board Games, Video Games)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Video Game Character Figurine", "Small figurines of characters from popular games, as collectibles or decorations", ["Gaming (e.g., Board Games, Video Games)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Custom Gaming-themed Bookmarks", "Bookmarks with gaming designs for marking progress in books or magazines", ["Gaming (e.g., Board Games, Video Games)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Gaming Console Cookie Cutter", "Cookie cutters in shapes of gaming consoles or controllers", ["Gaming (e.g., Board Games, Video Games)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
    
        ["Game Controller Cookie Cutters", "Cookie cutters shaped like game controllers or iconic gaming symbols", ["Gaming (e.g., Board Games, Video Games)", "Cooking or Baking"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Video Game-themed Apron", "An apron featuring popular video game characters or symbols", ["Gaming (e.g., Board Games, Video Games)", "Cooking or Baking"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Gaming Recipe Cards", "Blank recipe cards featuring borders or decorations related to gaming", ["Gaming (e.g., Board Games, Video Games)", "Cooking or Baking"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Edible Game-themed Cake Decorations", "Edible decorations for cakes or cupcakes, inspired by popular video games", ["Gaming (e.g., Board Games, Video Games)", "Cooking or Baking"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Gamer’s Cooking Mitt", "Oven mitts designed with prints or patterns related to gaming", ["Gaming (e.g., Board Games, Video Games)", "Cooking or Baking"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
        ["Video Game-themed Silicone Molds", "Silicone molds for chocolates or ice, featuring shapes from popular video games", ["Gaming (e.g., Board Games, Video Games)", "Cooking or Baking"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Gaming-themed Lunch Box", "A lunch box featuring designs from popular games for carrying meals", ["Gaming (e.g., Board Games, Video Games)", "Cooking or Baking"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Gamer Snack Clips", "Bag clips for snacks featuring designs inspired by video game elements", ["Gaming (e.g., Board Games, Video Games)", "Cooking or Baking"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Game Console Cutting Board", "A cutting board designed to look like a popular gaming console", ["Gaming (e.g., Board Games, Video Games)", "Cooking or Baking"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
        ["Video Game Character Baking Mats", "Silicone baking mats featuring outlines of popular video game characters for themed cookies", ["Gaming (e.g., Board Games, Video Games)", "Cooking or Baking"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
    
        ["Anime-themed Coloring Book", "A coloring book featuring various anime characters and scenes", ["Anime/Manga", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Manga Drawing Stencils", "Stencils to help in drawing popular manga characters or elements", ["Anime/Manga", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Anime Character Paint by Numbers", "A paint by numbers kit featuring popular anime characters", ["Anime/Manga", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Chibi-style Clay Modeling Kit", "A clay modeling kit to create chibi versions of popular anime characters", ["Anime/Manga", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Anime-themed Sketch Pads", "Sketch pads with anime character covers or watermarked pages", ["Anime/Manga", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Manga Drawing Pens", "Special drawing pens that are commonly used in manga art", ["Anime/Manga", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Anime Sticker Sets for Customization", "Stickers of various anime characters or elements for customizing art supplies", ["Anime/Manga", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Manga Art Technique Book", "A book showcasing various manga art techniques and tutorials", ["Anime/Manga", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Anime-inspired Washi Tapes", "Washi tapes with designs inspired by various anime for decorating and crafts", ["Anime/Manga", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Manga Character Drawing Templates", "Templates for drawing various poses of manga characters", ["Anime/Manga", "Artistic Activities (e.g., Drawing, Painting, Crafting)"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],

        ["Anime-themed USB Flash Drive", "A USB flash drive featuring designs or figures from popular anime", ["Anime/Manga", "Tech and Gadgets"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Manga-style Laptop Stickers", "Stickers featuring manga art or characters to personalize laptops or tablets", ["Anime/Manga", "Tech and Gadgets"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Anime Character Phone Stand", "A phone stand designed as popular anime characters", ["Anime/Manga", "Tech and Gadgets"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Anime-themed Mouse Pad", "A mouse pad featuring artwork or characters from popular anime", ["Anime/Manga", "Tech and Gadgets"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Anime Bluetooth Speaker", "A compact Bluetooth speaker featuring designs inspired by anime characters", ["Anime/Manga", "Tech and Gadgets"], ["Young Adult", "Adult"], [], "More Practical", "both", "both"],
        ["Manga Art Tablet Cover", "A cover for art tablets with prints of manga art or characters", ["Anime/Manga", "Tech and Gadgets"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Anime-inspired Earphone Case", "An earphone carrying case with designs inspired by popular anime", ["Anime/Manga", "Tech and Gadgets"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Chibi Anime Phone Charms", "Phone charms featuring chibi versions of popular anime characters", ["Anime/Manga", "Tech and Gadgets"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Anime Character Screen Cleaner", "A screen cleaner designed like an anime character, for phones or tablets", ["Anime/Manga", "Tech and Gadgets"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Manga-inspired Keyboard Stickers", "Stickers inspired by manga to customize and decorate computer keyboards", ["Anime/Manga", "Tech and Gadgets"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
    
        ["Anime-themed Jigsaw Puzzle", "Jigsaw puzzles that depict scenes or characters from popular anime or manga", ["Anime/Manga", "Puzzle Solving"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Manga Sudoku Book", "Sudoku puzzles book with manga-inspired designs and illustrations", ["Anime/Manga", "Puzzle Solving"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Anime Character Rubik’s Cube", "A variation of the classic Rubik’s Cube puzzle, featuring anime character images", ["Anime/Manga", "Puzzle Solving"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Manga-inspired Crossword Book", "A crossword puzzle book with themes and words commonly found in manga", ["Anime/Manga", "Puzzle Solving"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Anime Puzzle Keychain", "Keychains featuring mini-puzzles or maze games with an anime theme", ["Anime/Manga", "Puzzle Solving"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Anime Mystery Puzzle Box", "A puzzle box with anime themes that you have to solve to open", ["Anime/Manga", "Puzzle Solving"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Manga Word Search Book", "Word search puzzles focusing on terms, titles, and names associated with manga", ["Anime/Manga", "Puzzle Solving"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Anime-themed Logic Puzzles", "Book of logic puzzles inspired by various anime genres and series", ["Anime/Manga", "Puzzle Solving"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Anime-inspired Puzzle Cube", "A puzzle cube featuring colors or images related to popular anime series", ["Anime/Manga", "Puzzle Solving"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Manga-themed Brain Teasers Book", "A book filled with brain teasers and puzzles inspired by manga stories", ["Anime/Manga", "Puzzle Solving"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],

        ["Anime-themed Camera Strap", "A camera strap featuring designs from popular anime or manga", ["Anime/Manga", "Photography"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Manga-inspired Photo Album", "A photo album decorated with manga-inspired designs or illustrations", ["Anime/Manga", "Photography"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Anime Character Lens Cap", "A camera lens cap designed to look like a popular anime character or symbol", ["Anime/Manga", "Photography"], ["Young Adult", "Adult"], [], "More Practical", "both", "both"],
        ["Anime-themed Film Filters", "Transparent film filters with anime designs to add creative effects to photographs", ["Anime/Manga", "Photography"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Manga Drawing Photography Backdrop", "A backdrop featuring manga drawings, suitable for portrait photography", ["Anime/Manga", "Photography"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Anime-inspired Photo Frames", "Photo frames featuring design elements from popular anime", ["Anime/Manga", "Photography"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Chibi Anime Camera Case", "A camera case featuring chibi versions of popular anime characters", ["Anime/Manga", "Photography"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Anime Character Photo Props", "Cardboard photo props designed like anime characters for fun photography", ["Anime/Manga", "Photography"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Manga-style Photography Book", "A book featuring photographs inspired by manga art and storytelling", ["Anime/Manga", "Photography"], ["Young Adult", "Adult"], [], "More Practical", "both", "both"],
        ["Anime-themed Camera Stickers", "Stickers featuring anime characters to customize and decorate cameras", ["Anime/Manga", "Photography"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],

        ["Anime-themed Popcorn Bowl", "A popcorn bowl featuring artwork or characters from popular anime", ["Anime/Manga", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Manga Movie Marathon Guide", "A guidebook suggesting manga-based movies or series to watch", ["Anime/Manga", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Anime Character Headphones", "Headphones featuring designs inspired by popular anime characters", ["Anime/Manga", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Anime-inspired Playlist Compilation", "A compilation of music playlists inspired by various anime series", ["Anime/Manga", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Manga-themed DVD Storage Box", "A storage box for DVDs or Blu-rays with manga-themed designs", ["Anime/Manga", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Anime Series Synopsis Book", "A book providing synopses and reviews of various anime series and movies", ["Anime/Manga", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Anime Art Movie Posters", "Movie posters featuring anime art for decorating viewing areas", ["Anime/Manga", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Anime-themed Coaster Set", "A set of coasters featuring anime characters or artwork for use during media consumption", ["Anime/Manga", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Manga Adaptation Recommendation List", "A curated list of must-watch adaptations of popular manga", ["Anime/Manga", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Anime Quote Wall Art", "Wall art featuring inspiring or popular quotes from various anime", ["Anime/Manga", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
    
        ["Anime-themed Cookie Cutters", "Cookie cutters in the shape of popular anime characters or symbols", ["Anime/Manga", "Cooking or Baking"], ["Child", "Teen"], ["Birthday", "Christmas", "Easter"], "More Practical", "both", "both"],
        ["Manga-inspired Recipe Book", "A recipe book featuring dishes inspired by or seen in various manga", ["Anime/Manga", "Cooking or Baking"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Anime Character Apron", "An apron featuring prints of popular anime characters or series", ["Anime/Manga", "Cooking or Baking"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Bento Box with Anime Designs", "A Bento box for carrying meals, decorated with anime themes or characters", ["Anime/Manga", "Cooking or Baking"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Manga-themed Cake Molds", "Silicone cake molds featuring designs inspired by manga art or characters", ["Anime/Manga", "Cooking or Baking"], ["Teen", "Adult"], ["Birthday", "Christmas", "Easter"], "More Practical", "both", "both"],
        ["Anime-inspired Chopsticks", "A pair of chopsticks featuring anime characters or decorative elements related to anime", ["Anime/Manga", "Cooking or Baking"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Anime Character Baking Stencils", "Stencils for decorating cakes or cookies with anime character designs", ["Anime/Manga", "Cooking or Baking"], ["Teen", "Adult"], ["Birthday", "Christmas", "Easter"], "More Practical", "both", "both"],
        ["Anime-themed Kitchen Timer", "A kitchen timer designed to look like a popular anime character or item", ["Anime/Manga", "Cooking or Baking"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Manga-inspired Coasters", "Coasters featuring manga designs to be used during meal times", ["Anime/Manga", "Cooking or Baking"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Anime-themed Lunch Bag", "An insulated lunch bag with anime characters or themes for carrying meals", ["Anime/Manga", "Cooking or Baking"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
    
        ["Digital Stylus Pencil", "A stylus pencil for digital drawing or designing on tablets or smartphones", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Tech and Gadgets"], ["Teen", "Young Adult", "Adult"], [], "More Practical", "both", "both"],
        ["LED Tracing Pad", "A thin, light-up pad that assists in tracing and sketching designs", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Tech and Gadgets"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Tech-themed Sketch Book", "A sketchbook with a tech-inspired cover or tech-related drawing prompts inside", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Tech and Gadgets"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["3D Pen", "A pen that creates 3D drawings using plastic filaments, bringing designs to life", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Tech and Gadgets"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Reusable Smart Notebook", "A notebook that allows drawings to be digitally uploaded and the pages reused", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Tech and Gadgets"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Coloring Apps Subscription", "A subscription to premium features of coloring or drawing apps", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Tech and Gadgets"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Customizable Tech Decals", "Decals for customizing tech gadgets, which can be colored or designed", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Tech and Gadgets"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["VR Art Apps", "Virtual Reality apps that allow for immersive drawing and designing experiences", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Tech and Gadgets"], ["Teen", "Young Adult", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Digital Art Courses Subscription", "A subscription to online courses focused on digital art techniques and tools", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Tech and Gadgets"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Tech-inspired Craft Kits", "Craft kits inspired by tech elements, like creating pixel art or robot models", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Tech and Gadgets"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
    
        ["Paint-by-Number Puzzle", "A puzzle where each piece is painted according to numbered instructions", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Puzzle Solving"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Artistic Jigsaw Puzzle", "A jigsaw puzzle featuring a beautiful or famous piece of artwork", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Puzzle Solving"], ["Teen", "Adult", "Senior"], [], "More Enjoyable", "both", "both"],
        ["Puzzle-themed Sketch Pad", "A sketch pad with puzzle-inspired borders or backgrounds", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Puzzle Solving"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["3D Sculpture Puzzle", "A puzzle that forms a 3D sculpture, which can be painted or decorated afterwards", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Puzzle Solving"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Maze Drawing Book", "A book filled with mazes that can be solved and then colored or decorated", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Puzzle Solving"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Art Puzzle Lock", "A complex lock puzzle that is also a beautiful piece of art when solved", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Puzzle Solving"], ["Adult", "Senior"], [], "More Enjoyable", "both", "both"],
        ["Puzzle Assembly Mat", "A mat for assembling puzzles that also allows for artistic customization", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Puzzle Solving"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Customizable Puzzle Pieces", "Blank puzzle pieces that can be customized with drawings or writings before assembly", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Puzzle Solving"], ["Child", "Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Creative Sudoku Book", "A Sudoku book with artistic elements or backgrounds for coloring after solving", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Puzzle Solving"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Art-based Logic Puzzles", "Logic puzzles that result in a picture or design once solved", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Puzzle Solving"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
    
        ["Photo Coloring Book", "A coloring book featuring black and white photographs to be colored", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Photography"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Photography-themed Paint by Numbers", "A paint-by-number set based on a beautiful photograph", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Photography"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Customizable Camera Strap", "A camera strap that can be customized with paints or other artistic mediums", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Photography"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Photo Display Clips String", "A string with clips to artistically display various photographs", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Photography"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Photography Sketchbook", "A sketchbook with photography-related outer designs or printed photographs inside", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Photography"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["DIY Photo Album Kit", "A kit to create and customize a personal photo album with various artistic materials", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Photography"], ["Child", "Teen", "Adult"], ["Birthday", "Christmas", "Anniversary"], "More Enjoyable", "both", "both"],
        ["Photographer's Coloring Book", "A coloring book with intricate camera and photography-related designs", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Photography"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Film Negative Frame", "A frame designed to hold and display film negatives artistically", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Photography"], ["Adult", "Senior"], [], "More Enjoyable", "both", "both"],
        ["Custom Photo Puzzle", "A puzzle created from a personal photograph, which can be colored or decorated further", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Photography"], ["Child", "Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Photo-themed Stencil Set", "Stencils with various photography and camera designs for artistic projects", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Photography"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
    
        ["Film or Music Icon Paint-by-Numbers", "A paint-by-number kit featuring icons from movies or music", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Customizable CD or DVD Covers", "Blank covers to creatively design and customize music or movie collections", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["TV/Movie Themed Coloring Book", "A coloring book featuring scenes or characters from popular movies or TV shows", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Lyric or Quote Art Canvas", "A small, blank canvas to create artwork based on favorite movie quotes or song lyrics", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["DIY Popcorn Box", "A set to create and decorate personal popcorn boxes for movie nights", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], ["Birthday", "Christmas", "Other/No Specific Occasion"], "More Practical", "both", "both"],
        ["Film or Music Inspired Craft Kit", "Craft kits inspired by popular media, such as creating band logos or movie-themed crafts", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Create Your Own Movie Poster", "Materials and guidance to design and create a personal movie poster", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["DIY Musical Instrument Craft", "A simple craft kit to create a basic musical instrument and decorate it", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Customizable Playlist or Mixtape Cards", "Cards to design and list songs or movies, mimicking the style of old mixtapes or playlists", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], ["Birthday", "Anniversary", "Other/No Specific Occasion"], "More Practical", "both", "both"],
        ["Media-themed Embroidery Kit", "An embroidery kit featuring designs inspired by movies, music, or other media", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Adult", "Senior"], [], "More Enjoyable", "both", "both"],
    
        ["DIY Cookie Decorating Kit", "A set of plain cookies with edible colors for decorating", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Cooking or Baking"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Customizable Apron", "A plain apron that one can customize using fabric paints or markers", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Cooking or Baking"], ["Teen", "Adult", "Senior"], [], "More Enjoyable", "both", "both"],
        ["Food Coloring Set", "A set of various food colors for baking and cooking creativity", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Cooking or Baking"], ["Child", "Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Edible Art Decorations", "Edible decorations like flowers or figures for cake or cupcake decorating", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Cooking or Baking"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Cookbook with Illustrated Recipes", "A cookbook that has artistic illustrations along with the recipes", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Cooking or Baking"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
        ["Artistic Silicone Baking Molds", "Silicone molds with artistic patterns for cakes, chocolates, or other baked goods", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Cooking or Baking"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Decorative Plating Tools", "Tools that help in plating food in a more decorative and artistic way", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Cooking or Baking"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
        ["Art-themed Cookie Cutters", "Cookie cutters in shapes related to art, like paintbrushes, palettes, etc.", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Cooking or Baking"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["DIY Cake Stand", "Materials to create a personalized cake stand with decorative elements", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Cooking or Baking"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Food Presentation Book", "A book with ideas and techniques for presenting dishes artistically", ["Artistic Activities (e.g., Drawing, Painting, Crafting)", "Cooking or Baking"], ["Adult", "Senior"], [], "More Enjoyable", "both", "both"],

        ["Photo Puzzle", "A puzzle created from a personal or stock photograph", ["Puzzle Solving", "Photography"], ["Child", "Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Photography Scavenger Hunt", "A set of cards or a book with photography challenges that also involve solving clues or puzzles", ["Puzzle Solving", "Photography"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Camera Lens Puzzle", "A 3D puzzle that, when assembled, looks like a camera lens", ["Puzzle Solving", "Photography"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Puzzle Photo Frame", "A photo frame that the recipient can assemble like a puzzle", ["Puzzle Solving", "Photography"], ["Child", "Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Spot the Difference – Photography Edition", "A book filled with photographs where you have to spot the differences", ["Puzzle Solving", "Photography"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Photo Collage Jigsaw Puzzle", "A jigsaw puzzle made from a collage of various photographs", ["Puzzle Solving", "Photography"], ["Teen", "Adult", "Senior"], [], "More Enjoyable", "both", "both"],
        ["Mystery Photo Puzzle", "A puzzle that reveals a mysterious or surprising photograph when solved", ["Puzzle Solving", "Photography"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Picture Sudoku with Photographs", "Sudoku puzzles that use photographs instead of numbers", ["Puzzle Solving", "Photography"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["DIY Photo Rubik’s Cube", "A Rubik’s Cube that can be customized with personal photographs", ["Puzzle Solving", "Photography"], ["Teen", "Young Adult"], [], "More Practical", "both", "both"],
        ["Photography-themed Crossword or Puzzle Book", "A book of crosswords or other puzzles that are themed around photography terminology and concepts", ["Puzzle Solving", "Photography"], ["Teen", "Adult", "Senior"], [], "More Enjoyable", "both", "both"],
    
        ["Movie Mystery Puzzle", "A puzzle that, once solved, unfolds a mystery related to a popular movie or TV show", ["Puzzle Solving", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Trivia Game of Movies and TV Shows", "A trivia game where questions are focused on movies and TV shows", ["Puzzle Solving", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult", "Senior"], [], "More Enjoyable", "both", "both"],
        ["Music-themed Crossword Puzzle Book", "A book of crossword puzzles that are centered around music and bands", ["Puzzle Solving", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Pop Culture Sudoku", "Sudoku puzzles that incorporate elements from movies, TV shows, or music", ["Puzzle Solving", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Customizable Puzzle of Favorite Show Poster", "A blank puzzle that can be customized by printing a poster of a favorite show or movie", ["Puzzle Solving", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Movie or Music Star Jigsaw Puzzle", "A jigsaw puzzle featuring popular movie or music stars", ["Puzzle Solving", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Decoding Lyrics Game", "A game where players decode or interpret different song lyrics", ["Puzzle Solving", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["TV Show-themed Word Search", "Word search puzzles themed with words related to popular TV shows", ["Puzzle Solving", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Movie or Series Plot Puzzle", "A puzzle where you unravel the plot or mystery in a movie or series", ["Puzzle Solving", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
        ["Music Album Cover Puzzle", "A puzzle consisting of pieces that form famous music album covers", ["Puzzle Solving", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
    
        ["Recipe Mystery Box", "A box containing puzzle pieces that, when solved, reveal a unique recipe", ["Puzzle Solving", "Cooking or Baking"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Cooking Measurement Conversion Magnet", "A fridge magnet that provides measurement conversions in a puzzle-like design", ["Puzzle Solving", "Cooking or Baking"], ["Adult", "Senior"], [], "More Enjoyable", "both", "both"],
        ["Ingredient Riddle Cards", "Cards with riddles that hint at various ingredients for a recipe", ["Puzzle Solving", "Cooking or Baking"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Cookie Cutter Puzzle Pieces", "Cookie cutters in the shape of puzzle pieces", ["Puzzle Solving", "Cooking or Baking"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Culinary Quiz Game", "A game involving questions or quizzes related to culinary arts", ["Puzzle Solving", "Cooking or Baking"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Food-themed Sudoku or Crossword", "Sudoku or crossword puzzles themed around cooking or baking terminologies", ["Puzzle Solving", "Cooking or Baking"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Herb or Spice Puzzle", "Puzzle pieces that come together to show different herbs or spices", ["Puzzle Solving", "Cooking or Baking"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
        ["DIY Baking Kit with Puzzles", "A baking kit where the process involves solving small puzzles to proceed with the recipe", ["Puzzle Solving", "Cooking or Baking"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Cookbook with Puzzle Challenges", "A cookbook that includes puzzle challenges related to the recipes", ["Puzzle Solving", "Cooking or Baking"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Edible Puzzle Pieces Molds", "Silicone molds designed to create edible puzzle pieces for desserts or candies", ["Puzzle Solving", "Cooking or Baking"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],

        ["Film Directors' Photography Book", "A book showcasing the photography of renowned film directors", ["Photography", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Photo Clips LED Lights", "LED lights with clips to attach and illuminate photographs, perfect for displaying favorite movie or music moments", ["Photography", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Young Adult"], [], "More Enjoyable", "both", "both"],
        ["Photography in Movies Poster", "A poster that highlights iconic photography moments in movies", ["Photography", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Customizable CD/DVD Photo Covers", "Blank CD/DVD covers that can be customized with personal photographs, ideal for movie or music collections", ["Photography", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Movie Scenes Photography Book", "A book that focuses on the art of photography in various iconic movie scenes", ["Photography", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
        ["Photo Film Bookmarks", "Bookmarks designed like film negatives, suitable for marking pages in books, scripts, or film magazines", ["Photography", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Classic Movie Posters Puzzle", "A jigsaw puzzle featuring a collage of classic movie posters", ["Photography", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Music Album Photography Collection", "A collection or book highlighting the photography of iconic music album covers", ["Photography", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Young Adult", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Photo Collage Movie Posters", "A set of movie posters made from a collage of various scene photographs", ["Photography", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Cinematography Themed Photo Album", "A photo album with a design or theme based on cinematography for storing personal photographs", ["Photography", "Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"], ["Teen", "Adult", "Senior"], [], "More Enjoyable", "both", "both"],
    
        ["Food Photography Book", "A book focused on techniques and tips for capturing stunning food photographs", ["Photography", "Cooking or Baking"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Photography-themed Apron", "An apron with prints of cameras or photography-related items, ideal for someone who loves cooking and photography", ["Photography", "Cooking or Baking"], ["Adult", "Senior"], [], "More Enjoyable", "both", "both"],
        ["Edible Photo Cupcake Toppers", "Edible toppers for cupcakes or cakes that can be customized with personal photographs", ["Photography", "Cooking or Baking"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Camera Lens Coffee Mug", "A coffee mug designed to look like a camera lens, suitable for photographers who also enjoy baking or cooking", ["Photography", "Cooking or Baking"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Photo Recipe Cards", "Recipe cards that come with space for attaching photographs of the finished dish", ["Photography", "Cooking or Baking"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
        ["Photography Props for Food", "A set of props or backgrounds to enhance the presentation of food photographs", ["Photography", "Cooking or Baking"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Photo Frame Oven Mitts", "Oven mitts designed with a pocket to insert personal photos or images", ["Photography", "Cooking or Baking"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
        ["Cookie Cutter in Camera Shapes", "Cookie cutters designed in various camera or photography-related shapes", ["Photography", "Cooking or Baking"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Photographer’s Cookbook", "A cookbook featuring recipes accompanied by exceptional photography", ["Photography", "Cooking or Baking"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Food Styling Kit for Photography", "A kit that includes tools and accessories to style food for photography", ["Photography", "Cooking or Baking"], ["Adult", "Senior"], [], "More Enjoyable", "both", "both"],
    
        ["Film-themed Recipe Book", "A cookbook containing recipes inspired by various movies or TV shows", ["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)", "Cooking or Baking"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Popcorn Seasoning Set", "A variety of popcorn seasonings to enhance movie-watching experiences", ["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)", "Cooking or Baking"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Musical Playlist for Cooking", "A curated musical playlist CD to listen to while cooking, inspired by favorite movies or TV shows", ["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)", "Cooking or Baking"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["Movie Night Baking Kit", "A kit containing essentials for baking treats perfect for a movie night at home", ["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)", "Cooking or Baking"], ["Child", "Teen"], [], "More Enjoyable", "both", "both"],
        ["Edible Movie Quotes", "Edible decorations for cakes or cupcakes featuring famous quotes from movies", ["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)", "Cooking or Baking"], ["Teen", "Adult"], [], "More Practical", "both", "both"],
        ["TV Show-themed Cooking Apron", "A cooking apron featuring popular references or images from a beloved TV show", ["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)", "Cooking or Baking"], ["Adult", "Senior"], [], "More Enjoyable", "both", "both"],
        ["Cinema Snack Molds", "Silicone molds for creating cinema-themed snacks or chocolates", ["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)", "Cooking or Baking"], ["Child", "Teen"], [], "More Practical", "both", "both"],
        ["Film Reel Cupcake Stand", "A cupcake stand designed to look like a film reel, perfect for showcasing baked goods during a movie night", ["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)", "Cooking or Baking"], ["Teen", "Adult"], [], "More Enjoyable", "both", "both"],
        ["Movie Genre Spice Labels", "Spice labels designed with names or icons representing different movie genres", ["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)", "Cooking or Baking"], ["Adult", "Senior"], [], "More Practical", "both", "both"],
        ["Podcast-themed Kitchen Towels", "Kitchen towels printed with popular podcast logos or quotes, blending media and cooking interests", ["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)", "Cooking or Baking"], ["Young Adult", "Adult"], [], "More Enjoyable", "both", "both"],
    
        ["Bookmark","Creative bookmarks with unique designs.",["Reading (e.g., Fiction, Non-fiction)"],["Child","Teen"],[],"More Practical","both","both"],
        ["Book Light","Clip-on, adjustable book light for reading in dim areas.",["Reading (e.g., Fiction, Non-fiction)"],["Teen","Young Adult","Adult","Senior"],["Birthday","Christmas","Other/No Specific Occasion"],"More Practical","both","both"],
        ["Magnetic Page Markers","Decorative page markers to hold the page in books.",["Reading (e.g., Fiction, Non-fiction)"],["Child","Teen"],[],"More Enjoyable","both","both"],
        ["Book Sleeves","Protective sleeves for keeping books safe while traveling.",["Reading (e.g., Fiction, Non-fiction)"],["Teen","Young Adult","Adult"],["Birthday","Christmas","Other/No Specific Occasion"],"More Practical","both","both"],
        ["Story Cubes","Dice with pictures for creating own stories.",["Reading (e.g., Fiction, Non-fiction)"],["Child"],[],"More Enjoyable","both","both"],
        ["Funky Pencils","Themed pencils to make note-taking more interesting.",["Reading (e.g., Fiction, Non-fiction)"],["Child","Teen"],[],"More Enjoyable","both","both"],
        ["Reading Journal","A journal specifically designed for book lovers.",["Reading (e.g., Fiction, Non-fiction)"],["Teen","Young Adult","Adult"],["Birthday","Christmas","New Year"],"More Practical","both","both"],
        ["Decorative Sticky Notes","Themed sticky notes for annotating while reading.",["Reading (e.g., Fiction, Non-fiction)"],["Teen","Young Adult"],[],"More Enjoyable","both","both"],
        ["Book Holder","A tool that holds a book open, making reading easier.",["Reading (e.g., Fiction, Non-fiction)"],["Adult","Senior"],["Birthday","Christmas","Other/No Specific Occasion"],"More Practical","both","both"],
        ["Themed Coasters","Book-themed coasters for a reading nook.",["Reading (e.g., Fiction, Non-fiction)"],["Adult","Senior"],[],"More Enjoyable","both","both"],
    
        ["Dice Set","A colorful set of dice for board games.",["Gaming (e.g., Board Games, Video Games)"],["Child","Teen","Young Adult"],[],"More Enjoyable","both","both"],
        ["Card Sleeves","Protective sleeves for gaming cards.",["Gaming (e.g., Board Games, Video Games)"],["Teen","Young Adult","Adult"],[],"More Practical","both","both"],
        ["Mini Puzzles","Small puzzles related to popular games.",["Gaming (e.g., Board Games, Video Games)"],["Child","Teen"],[],"More Enjoyable","both","both"],
        ["Game Themed Keychains","Keychains themed around popular games.",["Gaming (e.g., Board Games, Video Games)"],["Teen","Young Adult"],["Birthday","Christmas","Other/No Specific Occasion"],"More Practical","both","both"],
        ["Gaming Posters","Posters of popular video games.",["Gaming (e.g., Board Games, Video Games)"],["Teen","Young Adult"],[],"More Enjoyable","both","both"],
        ["Board Game Upgrade Pieces","Enhanced pieces to replace basic ones in board games.",["Gaming (e.g., Board Games, Video Games)"],["Adult","Senior"],[],"More Practical","both","both"],
        ["Dice Bag","A bag to hold and carry game dice.",["Gaming (e.g., Board Games, Video Games)"],["Teen","Young Adult","Adult"],[],"More Practical","both","both"],
        ["Game-themed Stickers","Stickers related to popular video and board games.",["Gaming (e.g., Board Games, Video Games)"],["Child","Teen"],[],"More Enjoyable","both","both"],
        ["Wrist Rest","A rest pad for gamers who use computers.",["Gaming (e.g., Board Games, Video Games)"],["Young Adult","Adult"],["Birthday","Christmas","Other/No Specific Occasion"],"More Practical","both","both"],
        ["Custom Game Tokens","Personalized tokens for board games.",["Gaming (e.g., Board Games, Video Games)"],["Adult","Senior"],[],"More Enjoyable","both","both"],
      
        ["Anime Stickers","Various stickers featuring popular anime characters.",["Anime/Manga"],["Child","Teen"],[],"More Enjoyable","both","both"],
        ["Manga Drawing Pencils","Special pencils for manga drawing.",["Anime/Manga"],["Teen","Young Adult"],[],"More Practical","both","both"],
        ["Chibi Keychains","Keychains featuring chibi versions of anime characters.",["Anime/Manga"],["Child","Teen","Young Adult"],[],"More Enjoyable","both","both"],
        ["Anime-themed Badges","Badges featuring popular anime logos or characters.",["Anime/Manga"],["Teen","Young Adult"],[],"More Practical","both","both"],
        ["Poster of Popular Anime","Posters of scenes or characters from popular anime.",["Anime/Manga"],["Teen","Young Adult"],[],"More Enjoyable","both","both"],
        ["Mini Figurines","Small figurines of popular anime characters.",["Anime/Manga"],["Child","Teen"],[],"More Practical","both","both"],
        ["Anime-themed Bookmarks","Bookmarks featuring popular anime characters.",["Anime/Manga"],["Child","Teen"],[],"More Practical","both","both"],
        ["Cosplay Accessories","Small accessories that can be used for simple cosplay.",["Anime/Manga"],["Teen","Young Adult"],["Birthday","Christmas","Other/No Specific Occasion"],"More Enjoyable","both","both"],
        ["Manga Drawing Guide","A guidebook with tips for drawing manga.",["Anime/Manga"],["Teen","Young Adult"],[],"More Practical","both","both"],
        ["Japanese Learning Flashcards","Flashcards for learning basic Japanese words.",["Anime/Manga"],["Teen","Young Adult","Adult"],[],"More Enjoyable","both","both"],
    
        ["Sketching Pencils","A set of sketching pencils of various gradients.",["Artistic Activities (e.g., Drawing, Painting, Crafting)"],["Child","Teen","Young Adult"],[],"More Practical","both","both"],
        ["Acrylic Paint Set","A basic set of acrylic paints for artists.",["Artistic Activities (e.g., Drawing, Painting, Crafting)"],["Teen","Young Adult","Adult"],[],"More Enjoyable","both","both"],
        ["Mini Canvas and Easel","A small canvas and easel for quick paintings or displays.",["Artistic Activities (e.g., Drawing, Painting, Crafting)"],["All ages"],[],"More Enjoyable","both","both"],
        ["Crafting Scissors","Scissors with different edges for various cutting patterns.",["Artistic Activities (e.g., Drawing, Painting, Crafting)"],["Child","Teen"],[],"More Practical","both","both"],
        ["Stencils","Various stencils for drawing and crafting.",["Artistic Activities (e.g., Drawing, Painting, Crafting)"],["Child","Teen"],["Birthday","Christmas","Easter"],"More Practical","both","both"],
        ["Washi Tape","Decorative tape for various artistic and craft purposes.",["Artistic Activities (e.g., Drawing, Painting, Crafting)"],["Teen","Young Adult","Adult"],[],"More Enjoyable","both","both"],
        ["Origami Paper","Colored paper specifically for origami crafts.",["Artistic Activities (e.g., Drawing, Painting, Crafting)"],["Child","Teen"],["Birthday","Christmas","Easter"],"More Practical","both","both"],
        ["Paint Brushes","A set of paint brushes of various sizes and types.",["Artistic Activities (e.g., Drawing, Painting, Crafting)"],["Teen","Young Adult","Adult"],[],"More Enjoyable","both","both"],
        ["Embroidery Kit","A basic kit with essentials for someone to start embroidery.",["Artistic Activities (e.g., Drawing, Painting, Crafting)"],["Young Adult","Adult","Senior"],[],"More Practical","both","both"],
        ["Palette","A mixing palette for painters.",["Artistic Activities (e.g., Drawing, Painting, Crafting)"],["Teen","Young Adult","Adult"],[],"More Enjoyable","both","both"],

        ["Cable Organizers","Silicone cable organizers for managing various cables.",["Tech and Gadgets"],["Teen","Young Adult","Adult","Senior"],[],"More Practical","both","both"],
        ["Phone Stand","A small, portable stand to hold smartphones.",["Tech and Gadgets"],["All ages"],["Birthday","Christmas","Other/No Specific Occasion"],"More Enjoyable","both","both"],
        ["Screen Cleaning Kit","Kit for cleaning various screens like phones and laptops.",["Tech and Gadgets"],["All ages"],[],"More Practical","both","both"],
        ["USB LED Light","Portable LED light that can be plugged into USB ports.",["Tech and Gadgets"],["Teen","Young Adult","Adult"],[],"More Enjoyable","both","both"],
        ["Earphone Pouch","A pouch for storing earphones and preventing tangles.",["Tech and Gadgets"],["Teen","Young Adult","Adult"],[],"More Practical","both","both"],
        ["Keyboard Stickers","Decorative stickers for computer keyboards.",["Tech and Gadgets"],["Child","Teen"],[],"More Enjoyable","both","both"],
        ["Mouse Pad","Ergonomic mouse pads with wrist support.",["Tech and Gadgets"],["Young Adult","Adult","Senior"],[],"More Practical","both","both"],
        ["Wireless Charger","An affordable wireless charger for compatible devices.",["Tech and Gadgets"],["Young Adult","Adult","Senior"],["Birthday","Christmas","Anniversary"],"More Enjoyable","both","both"],
        ["Tech-themed Coasters","Coasters with tech and gadget-themed designs.",["Tech and Gadgets"],["Adult","Senior"],[],"More Practical","both","both"],
        ["VR Headset Stand","A stand to place and display VR headsets.",["Tech and Gadgets"],["Teen","Young Adult","Adult"],[],"More Enjoyable","both","both"],

        ["Mini Puzzle","Small-sized puzzles that are travel-friendly.",["Puzzle Solving"],["Child","Teen"],[],"More Enjoyable","both","both"],
        ["Sudoku Book","A book filled with Sudoku puzzles of varying difficulties.",["Puzzle Solving"],["Teen","Adult","Senior"],[],"More Practical","both","both"],
        ["Brain Teasers","Metal wire puzzles or wooden brain teaser puzzles.",["Puzzle Solving"],["All ages"],[],"More Enjoyable","both","both"],
        ["Crossword Book","A book filled with crossword puzzles.",["Puzzle Solving"],["Adult","Senior"],[],"More Practical","both","both"],
        ["Rubik’s Cube Keychain","A mini Rubik’s cube attached to a keychain.",["Puzzle Solving"],["Child","Teen"],[],"More Enjoyable","both","both"],
        ["Logic Puzzles Book","Book containing a variety of logic puzzles.",["Puzzle Solving"],["Teen","Adult","Senior"],[],"More Practical","both","both"],
        ["Jigsaw Puzzle Mat","Roll-up mat to save the progress of a jigsaw puzzle.",["Puzzle Solving"],["All ages"],[],"More Practical","both","both"],
        ["3D Puzzle","Small 3D puzzles that can be a fun challenge to solve.",["Puzzle Solving"],["Child","Teen"],[],"More Enjoyable","both","both"],
        ["Maze Ball","A ball inside a maze that needs to be solved.",["Puzzle Solving"],["Child","Teen"],[],"More Practical","both","both"],
        ["Puzzle Glue","Glue that helps to preserve completed puzzles.",["Puzzle Solving"],["Teen","Adult","Senior"],[],"More Enjoyable","both","both"],

        ["Lens Cleaning Kit","A kit to clean camera lenses for clearer photographs.",["Photography"],["Teen","Young Adult","Adult","Senior"],[],"More Practical","both","both"],
        ["Photo Clips String Lights","LED string lights with clips to hang and illuminate photos.",["Photography"],["Teen","Young Adult"],[],"More Enjoyable","both","both"],
        ["Camera Strap","A decorative and comfortable strap for carrying cameras.",["Photography"],["Teen","Young Adult","Adult"],[],"More Practical","both","both"],
        ["Film Canister Keychain","Keychain resembling a classic film canister.",["Photography"],["All ages"],[],"More Enjoyable","both","both"],
        ["Mini Tripod","A small, portable tripod suitable for basic photography needs.",["Photography"],["Teen","Young Adult","Adult"],[],"More Practical","both","both"],
        ["Photo Frame","Stylish photo frames to display cherished photographs.",["Photography"],["All ages"],["Birthday","Christmas","Anniversary"],"More Enjoyable","both","both"],
        ["Photography Themed Stickers","Stickers themed around cameras and photography.",["Photography"],["Child","Teen"],[],"More Enjoyable","both","both"],
        ["Photography Gloves","Special gloves that allow easy camera handling in cold weather.",["Photography"],["Adult","Senior"],[],"More Practical","both","both"],
        ["DIY Photo Album","An album where one can creatively arrange and display photos.",["Photography"],["All ages"],["Birthday","Christmas","Anniversary"],"More Enjoyable","both","both"],
        ["Camera Lens Mug","A mug that resembles a camera lens, suitable for hot beverages.",["Photography"],["Teen","Young Adult","Adult"],[],"More Practical","both","both"],

        ["Popcorn Boxes","Reusable popcorn boxes for a home movie night.",["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"],["All ages"],[],"More Enjoyable","both","both"],
        ["CD Sleeves","Protective sleeves to store and organize CDs.",["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"],["Teen","Young Adult","Adult","Senior"],[],"More Practical","both","both"],
        ["Movie Posters","Posters of classic or popular movies.",["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"],["Child","Teen","Young Adult"],[],"More Enjoyable","both","both"],
        ["Headphone Splitter","A device to connect multiple headphones to a single device.",["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"],["Teen","Young Adult"],[],"More Practical","both","both"],
        ["Mini Smartphone Projector","A simple projector to watch content from smartphones.",["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"],["Teen","Young Adult","Adult"],[],"More Enjoyable","both","both"],
        ["Vinyl Coasters","Coasters resembling classic vinyl records.",["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"],["Adult","Senior"],[],"More Practical","both","both"],
        ["TV Show Themed Keychains","Keychains themed after popular TV shows.",["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"],["Child","Teen","Young Adult"],[],"More Enjoyable","both","both"],
        ["Music Themed Pencils","Pencils engraved with quotes related to music or movies.",["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"],["Child","Teen"],[],"More Practical","both","both"],
        ["Bookmark with a Quote","Bookmarks featuring famous quotes from movies or series.",["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"],["All ages"],["Birthday","Christmas","Easter"],"More Enjoyable","both","both"],
        ["Bluetooth Speaker Stand","A stand to place smartphones and small Bluetooth speakers.",["Media Consumption (e.g., Movies, TV Shows, Music, Podcasts)"],["Teen","Young Adult","Adult"],[],"More Practical","both","both"],

        ["Silicone Baking Cups","Reusable silicone cups for muffins and cupcakes.",["Cooking or Baking"],["All ages"],["Birthday","Christmas","Easter"],"More Practical","both","both"],
        ["Spice Labels","Labels to organize and easily identify various spices.",["Cooking or Baking"],["Adult","Senior"],[],"More Practical","both","both"],
        ["Cookie Cutters","Set of cookie cutters in various shapes and sizes.",["Cooking or Baking"],["Child","Teen"],["Birthday","Christmas","Easter"],"More Enjoyable","both","both"],
        ["Egg Separator","A tool to easily separate egg yolks from whites.",["Cooking or Baking"],["Teen","Adult","Senior"],[],"More Practical","both","both"],
        ["Mini Whisks","Set of small whisks suitable for various kitchen tasks.",["Cooking or Baking"],["All ages"],[],"More Enjoyable","both","both"],
        ["Measuring Spoons","Set of spoons to accurately measure ingredients.",["Cooking or Baking"],["All ages"],[],"More Practical","both","both"],
        ["Silicone Pastry Brush","A brush for applying butter, oil, or glazes to baked goods.",["Cooking or Baking"],["Teen","Adult","Senior"],[],"More Enjoyable","both","both"],
        ["Bread Proofing Basket","Small basket for proofing bread dough.",["Cooking or Baking"],["Adult","Senior"],["Birthday","Christmas","Anniversary"],"More Practical","both","both"],
        ["Decorative Cupcake Wrappers","Themed wrappers to enhance the presentation of cupcakes.",["Cooking or Baking"],["Child","Teen"],["Birthday","Christmas","Easter"],"More Enjoyable","both","both"],
        ["Bamboo Skewers","Skewers suitable for grilling or arranging food items.",["Cooking or Baking"],["Teen","Adult","Senior"],["Birthday","Christmas","Other/No Specific Occasion"],"More Practical","both","both"]

        //Physical and other hobbies

        //General if they dont pick any interests

    ],

    //Under 10 euros
    [
        ["Dice Set","A colorful set of dice for board games.",["Gaming (e.g., Board Games, Video Games)"],["Child","Teen","Young Adult"],[],"More Enjoyable","both","both"]

    ],
    //Under 20 euros
    [
        ["Dice Set","A colorful set of dice for board games.",["Gaming (e.g., Board Games, Video Games)"],["Child","Teen","Young Adult"],[],"More Enjoyable","both","both"]

    ],
    //Under 50 euros
    [
        ["Dice Set","A colorful set of dice for board games.",["Gaming (e.g., Board Games, Video Games)"],["Child","Teen","Young Adult"],[],"More Enjoyable","both","both"]

    ]
]